config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
   authenticated :user do
     root 'links#index', as: :authenticated_root
   end

   unauthenticated do
     root 'static_pages#tour', as: :unauthenticated_root
   end
 end

 resources :links
 get '/url_stats/:id' => 'links#url_stats'
 
 resources :visits
 
 get '/:slug' => 'visits#create'

end

app/models/link.rb
class Link < ActiveRecord::Base
  
  validates :slug, presence: true
  validates :target_url, presence: true
  validates :slug, uniqueness: true

  belongs_to :user
  has_many :visits

  def standardize_target_url!
    self.target_url.gsub!("http://", "")
    self.target_url.gsub!("https://", "")
  end

  def visit_count
    self.visits.count
  end

  def map_url
    url = "http://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap>"
    self.visits.each do |visit|
     url = url + "&markers=color:blue%7C#{visit.latitude},#{visit.longitude}"
    end
    return url
  end 

  def total_visits_to_target_url
    total = 0
    Link.where(:target_url => self.target_url, :user_id => self.user_id).each do |link|
      total += link.visit_count 
    end 
    total
  end
 
  def target_url_stats
    stats_hash = {}
    Link.where(:target_url => self.target_url, :user_id => self.user_id).each do |link|
      stats_hash.merge!({link.description => link.visit_count})
    end 
    stats_hash
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visit.rb
class Visit < ActiveRecord::Base

  belongs_to :link

  geocoded_by :ip_address  
  after_validation :geocode
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_action :authenticate_user!

  def index
    @links = current_user.links
  end

  def show
    @links = current_user.links
    @link = current_user.links.find_by(:id => params[:id])

    unless @link
      flash[:warning] = "Link not found"
      redirect_to links_path
    end
  end

  def new
    @link = Link.new
  end

  def create
    @link = current_user.links.new(params[:link])
    @link.standardize_target_url!
    
    if @link.save
      flash[:success] = "You have a new shortlink!"
      redirect_to links_path
    else
      render 'new'
      #using redirect_to right here would clear the form. 
    end
  end

  def edit
    @link = Link.find_by(:id => params[:id])

    unless @link
      flash[:warning] = "Link not found"
      redirect_to links_path
    end
  end

  def update
    @link = Link.find_by(:id => params[:id])

    if @link && @link.update(params[:link])
      @link.standardize_target_url!
      flash[:success] = "Shortlink Updated!"
      redirect_to links_path
    else
      render 'edit'
    end
  end

  def destroy
    @link = current_user.links.find_by(:id => params[:id])
    @link.destroy

    if @link && @link.destroy
      flash[:success] = "Link destroyed successfully"
      redirect_to links_path
    else
      flash[:warning] = "Unsuccessful"
      redirect_to links_path
    end
  end

  def url_stats
    @links = current_user.links
    @link = current_user.links.find_by(:id => params[:id])

    unless @link
      flash[:warning] = "Link not found"
      redirect_to links_path
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def tour
  end

  
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def create
    @link = Link.find_by(:slug => params[:slug])
    if @link
      visit = @link.visits.create(:ip_address => request.remote_ip)

      redirect_to "http://#{@link.target_url}"
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortenerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid" id="main-navbar">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a id="logo" class="navbar-brand" href="/">url.mgr</a>

      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">
              <% if current_user.nil? %>
                <li><a href="/users/sign_up">Sign Up</a></li>
                <li><a href="/users/sign_in">Sign In</a></li>
              <% end %>

              <% if current_user %>
                <li><a href="/users/edit">Edit Profile</a></li>
                <li class="divider"></li>
                <li><a href="/users/sign_out" id="sign_out_link">Sign Out</a></li>
              <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container-fluid">

    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: "alert alert-#{name}" %>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/links/_form.html.erb
<% if @link.errors.any? %>
  <div id="error_explanation">
    <p>Whoops...there's <%= pluralize(@link.errors.count, "error") %> stopping this link from being saved:</p>
 
    <ul>
    <% @link.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for @link do |f| %>
  <%= f.input :description, label: "Briefly describe this link. \n (Example: tracking link for our ad on Forbes.com)" %>
  <%= f.input :slug, label: "What do you want at the end of the URL? (Example: name-of-company-1)" %>
  <%= f.input :target_url, label: "What URL do you want this new shortlink to go to?"%>
  <%= f.button :submit %>
<% end %>

app/views/links/edit.html.erb
<h1>Edit your Shortlink</h1>

<%= render "form" %>

app/views/links/index.html.erb
<h7>Hello, <%= current_user.email %>!</h7>

<h2 class="index-header">Here are all your links:</h2>

<div class="btn btn-success"><%= link_to "Create a new link", new_link_path %></div>

<table class="table table-hover index-table">
  <tr>
    <th>Description</th>
    <th>Slug (what's on the end of your shortlink)</th>
    <th>Target URL (where it goes to)</th>
    <th>Number of Clicks on It</th>
    <th> </th>
  </tr>
  <% @links.each do |link| %>
    <tr>
      <td><%= link_to link.description, link_path(link.id)%></td>
      <td><%= link_to link.slug, link_path(link.id) %></td>
      <td><a href="/url_stats/<%= link.id %>"><%= link.target_url %><a></td>
      <td> <%= link_to link.visit_count, link_path(link.id) %> </td>
      <td>
        <div class="btn btn-default"><%= link_to "Edit", edit_link_path(link.id) %></div>
        <div class="btn btn-danger"><%=link_to "Delete",link_path(link.id), 'data-method' => :delete, :class => "delete", :confirm => "Are you sure ?"%></div>
      </td>
    </tr>
  <% end %>
</table>

app/views/links/new.html.erb
<h1>Make a New Shortlink:</h1>

<% if @post && @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render "form" %>

app/views/links/show.html.erb
<h2>Link Stats for: <%= @link.slug%></h2>
<h3>Visits: <%= @link.visit_count %></h3>

<h4>Locations from which people have clicked this shortlink:</h4>

<div class='col-md-8'>
  <img class="link-map" src=<%= @link.map_url %>>
</div>

<div class="col=md-4">
  <table class="slug-data-table">
    <tr>
      <td class="words">Number of clicks on this shortlink:  </td> 
      <td><%= @link.visit_count %></td>
    </tr>
    <tr>
      <td class="words">Number of tracked clicks for the url this shorlink goes to:  </td>
      <td><%= @link.total_visits_to_target_url %></td>
    </tr>
    <tr>
      <td class="words">Percentage of tracked clicks to this site that came from this specific slug:  </td> 
      <td><%= '%.2f' % (100*(@link.visit_count.to_f/@link.total_visits_to_target_url.to_f)) %>%</td>
    </tr>
  </table>
</div>

app/views/links/url_stats.html.erb
<h3>Where your clicks are coming from to <%= link_to @link.target_url, link_path(@link.target_url)%>:</h3>

<div>
  <%= pie_chart @link.target_url_stats, library: {width: "400px", backgroundColor: "transparent", colors: ["blue", "red", "purple", "green", "orange", "black", "yellow"], pieHole: 0.4, pieSliceBorderColor: "#444"} %>
</div>

app/views/static_pages/tour.html.erb
<div class="tour-body">

  <div class="section">
    <h1>Track where your clicks come from,</h1>
    <h1>on the web and in the world.</h1>
  </div>

  <div class="tour section">
    <h3>Track clicks to your website, or any website.</h3>
    <%= image_tag("index-shot.png") %>
  </div>

  <div class="tour section">
    <h3>See how many clicks you get from each URL... and where in the world people are clicking from.</h3>
    <%= image_tag("show-shot.png") %>
  </div>

  <div class="tour section">
    <h3>Find out how your traffic breaks down across your shorlinks!</h3>
    <%= image_tag("url-stats-shot.png") %>
  </div>

  <div class="section">
    <div class="btn btn-default tour-btn"><%= link_to "Sign Up", "/users/sign_up" %></div>
  </div>
  
</div>